### ISSUE TITLE
Weirdness when rotate example is restarted

### ISSUE THREAD

**Issue by alexwarren** [textadventures/squiffy#39]
In http://docs.textadventures.co.uk/squiffy/rotate-sequence.html the examples work when the page is first loaded, but the order is then messed up after a restart.

**Comment by caberg** [comment]
laready test it using this code from example template of squiffy and run it on localhost
```
Choose a number: {rotate:one:two:three}

+++OK...

Now {rotate result:four:five:six}

+++OK...

You chose {result}.

Now for a sequence: {sequence:one:two:three:four:five}.

+++And another...

Another sequence: {sequence seqresult:a:b:c:d:e:f:g}.

+++Finally...

You chose {seqresult}.

Here's a sequence that links to another section. {sequence:Ready...:Steady...:[[Go!]]}

[[Go!]]:

That's all folks!
```
there's no weirdness , both rotate and sequence goes fine when i restart using restart link

**Comment by alexwarren** [comment]
Maybe it only happens where there are multiple games embedded in a page. You can definitely still reproduce the issue on the documentation page I mentioned.

**Comment by caberg** [comment]
maybe it is, i'll check again maybe there's something i can do

**Comment by ShadowKyogre** [comment]
@caberg , @alexwarren: I can confirm this bug works with just one game when I ran the sample @caberg gave in the [scratchpad](http://docs.textadventures.co.uk/squiffy/scratchpad/).

That being said, why is the text attribute being munged in these lines: https://github.com/textadventures/squiffy/blob/master/squiffy.template.js#L523-L532

Rather than tracking which position the rotate/sequence is in?

I noticed is that it always starts off at the first element, but then progresses to the next element that was after the "current" element before the restart, so maybe there's a part of the code where squiffy's forgetting to forget the rotation position.
